# Project Name
TARGET = Gumdrops

# Sources
CPP_SOURCES = Gumdrops.cpp \
../lib/ev_gui/menuItem.cpp \
../lib/ev_gui/menuItemInt.cpp \
../lib/ev_gui/menu.cpp \
../lib/ev_gui/fieldGui.cpp \
../lib/ev_theory/tempo.cpp \
../lib/ev_theory/theory.cpp \
../lib/ev_theory/midi.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Compiler flag to optimize for binary size.
OPT = -Os

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile