# Project Name
TARGET = Jellybeans

# Sources
CPP_SOURCES = Jellybeans.cpp
# Mu/logistics/menuitem.cpp \
# Mu/music/arp.cpp \
# Mu/music/chord.cpp \
# Mu/music/theory.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile