# Project Name
TARGET = Jellybeans

# Sources
CPP_SOURCES = Jellybeans.cpp \
theory.cpp \
menuitem.cpp \
arp.cpp \
chord.cpp


# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile